# @format

version: "3.0"

services:
  graphql-api:
    container_name: "wrestle-universe-search"
    volumes:
      - ./:/workspace:cached
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    working_dir: /workspace/src
    command: pipenv run uvicorn graphql_app:app --reload --port=8080 --host=0.0.0.0
    ports:
      - 10125:8080
    tty: true
